name: Build and Release

permissions:
  contents: write  # Grants write access to repository contents

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23' 

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Upload the built .jar as a release asset using softprops/action-gh-release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/mc-gtafasttravel-1.0.1.jar  # Adjust the path and filename as needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
