name: Build and Release

permissions:
  contents: write  # Grants write access to repository contents

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Get version from pom.xml
      - name: Get version from pom.xml
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # Step 5: Verify jar file path
      - name: List target directory
        run: ls -al target

      # Step 6: Upload the built .jar as a release asset using softprops/action-gh-release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/mc-gtafasttravel-${{ env.VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}